# Site Settings
#==================================
title: Beyond the Printed Page
email: egardner@getty.edu
description: Beyond the Printed Page
baseurl: "/beyond-the-printed-page" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
#==================================
markdown: redcarpet
redcarpet: 
  extensions: ["smart", "strikethrough"]

highlighter: pygments
exclude: [Gemfile, Gemfile.lock, readme.md]

# Permalinks
#==================================
permalink: /:year/:month/:day/:title/

# Assets
#==================================
sass:
  sass_dir: assets/styles/_scss  # default is _sass
  style: compressed # set to compressed for production

# Collections
#==================================
collections:
  issues:
    output: true
    permalink: /:path/


# Front-matter Defaults
#==================================
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"

# Prose Settings
#==================================
prose:
  ignore: ['.gitignore', '_config.yml', 'test.html', 'Gemfile', 'Gemfile.lock', 'assets', '_includes', '_layouts', '_data']
  metadata:
    _posts:
    - name: "Layout"
      field:
        element: "hidden"
        value: post
    - tags:
      field:
        element: "multiselect"
        label: "Add Tags"
        placeholder: "Choose Tags"
        alterable: true
    - date:
        field:
          element: hidden



