# Site Settings
#==================================
title: Beyond the Printed Page
email: egardner@getty.edu
description: Beyond the Printed Page
baseurl: "/beyond-the-printed-page" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
#==================================
markdown: redcarpet
redcarpet: 
  extensions: ["smart", "strikethrough"]

highlighter: pygments
exclude: [Gemfile, Gemfile.lock, readme.md]

# Permalinks
#==================================
permalink: /:year/:month/:day/:title/

# Assets
#==================================
sass:
  sass_dir: assets/styles/_scss  # default is _sass
  style: compressed # set to compressed for production

# Collections
#==================================
collections:
  issues:
    output: true
    permalink: /:path/


# Front-matter Defaults
#==================================
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"

# Prose Settings
#==================================
prose:
  ignore: ['.gitignore', '_config.yml', 'test.html', 'Gemfile', 'Gemfile.lock', 'assets', '_includes', '_layouts', '_data']
  media: "assets/img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Your Title Here"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "text"
          label: "Add Tags"
          placeholder: "conferences, epub, platforms..."
      - name: "date"
        field:
          element: "hidden"
      - name: "meta"
        field:
          element: "hidden"
      - name: "type"
        field:
          element: "hidden"
      - name: "status"
        field:
          element: "hidden"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "Uncheck to make this post hidden."
          value: true
          on: "true"
          off: "false"
